### ISSUE TITLE
(shortfin) Need debug-print support for f16 arrays and other types not supported array.array types

### ISSUE THREAD

**Issue by renxida** [nod-ai/SHARK-Platform#292]
Problem:
shortfin exports arrays to host via python's array.array which does not support float16. This is because python's array.array lib does not support float16 as a data type.

This is fine for running models as the output ends up in one of the supported dtypes, but for debugging it means that we can't print a lot of the things we encounter.

Supported types:

https://github.com/nod-ai/SHARK-Platform/blob/0c2e965c3ffe723db2fe2be9193c6d45fe558dbe/shortfin/python/array_binding.cc#L191-L205

Some messy reproducer code:
<details>
```python
import shortfin as sf
import shortfin.host
import shortfin.array as sfnp
import shortfin.amdgpu

gpu = False
if gpu:
    sc = sf.amdgpu.SystemBuilder()
else:
    sc = sf.host.CPUSystemBuilder()
lsys = sc.create_system()



def fiber(lsys):
    return lsys.create_fiber()


def device(fiber):
    return fiber.device(0)

fiber = fiber(lsys)

device = device(fiber)

dtype = sfnp.float16

value = 3.14

ary = sfnp.device_array.for_host(fiber.device(0), [2, 4], dtype)
with ary.map(discard=True) as m:
    m.fill(value)

hary = ary.items
print(hary)
```
</details>

**Comment by renxida** [comment]
I'm currently doing this:

```c
    add_type(DType::float16(), "H", sizeof(unsigned short)); // hack for dumping float16 values
```

And reinterpret-casting everything as float16s after i fetch them from device, but as @stellaraccident said, we probably don't want everyone doing this everywhere and we should have a more canonical way of doing this.

**Comment by ScottTodd** [comment]
How much do you need to actually extract f16 from the program and interact with it from your user code? Is that for debugging? We generally try to keep weird data types internal to the model and baseline support is just for loading from a file into memory and then running kernels with that data type.

**Comment by stellaraccident** [comment]
We can have some auxiliary functions to convert to numpy arrays if numpy is installed. The code is a little intricate but I've done it before.

**Comment by stbaione** [comment]
Closed with this PR: https://github.com/nod-ai/SHARK-Platform/pull/304
