### ISSUE TITLE
[shortfin] Use vm context forks in sf.Program invocations.

### ISSUE THREAD

**Issue by monorimet** [nod-ai/SHARK-Platform#324]
By default, we should make sure that concurrent vm function invocations are thread-safe.

This should be enabled by https://github.com/iree-org/iree/pull/18751 but we need shortfin to make use of iree_vm_context_fork API to avoid some sharp edges on pipelined workloads.

**Comment by stellaraccident** [comment]
Thanks for the reminder. I have a patch that is 99% done on this but was working locally on triaging a test case and forgot to push before getting on the road. Will clean up and send out.

**Comment by monorimet** [comment]
Addressed by https://github.com/nod-ai/SHARK-Platform/commit/187c45e03b44c92b37caff3f2d1ba615538f0e59
