### ISSUE TITLE
Update user guide/shark-ai package with fastapi, uvicorn, aiohttp

### ISSUE THREAD

**Issue by monorimet** [nod-ai/SHARK-Platform#533]
These requirements were not previously mentioned in the sd README, and now that we've migrated the requirements setup into the shark-ai[apps] package, we'll need to make sure they are added in for a seamless setup experience.

**Comment by monorimet** [comment]
FYI @amd-chrissosa

**Comment by ScottTodd** [comment]
Already fixed by https://github.com/nod-ai/SHARK-Platform/pull/529?
